syntax = "proto3";

import "google/protobuf/any.proto";

option java_package = "org.tron.p2p.protos";
option java_outer_classname = "Discover";

message Endpoint {
  bytes address = 1;
  int32 port = 2;
  bytes nodeId = 3;
  bytes addressIpv6 = 4;
}

message PingMessage {
  Endpoint from = 1;
  Endpoint to = 2;
  int32 version = 3;
  int64 timestamp = 4;
}

message PongMessage {
  Endpoint from = 1;
  int32 echo = 2;
  int64 timestamp = 3;
}

message FindNeighbours {
  Endpoint from = 1;
  bytes targetId = 2;
  int64 timestamp = 3;
}

message Neighbours {
  Endpoint from = 1;
  repeated Endpoint neighbours = 2;
  int64 timestamp = 3;
}

message EndPoints {
  repeated Endpoint nodes = 1;
}

message DnsRoot {
  message TreeRoot {
    bytes eRoot = 1;
    bytes lRoot = 2;
    int32 seq = 3;
  }
  TreeRoot treeRoot = 1;
  bytes signature = 2;
}

message Node {
  bytes nodeId = 1;
  bytes ip = 2;
  int32 port = 3;
  map<string, bytes>  meta = 10;
}

message Identity {
  Node node = 1;
  bytes nonce = 2;
  map<string, bytes> params = 10;
}

message Ping {
  bytes reqId = 1;
  bytes session = 2;
}

message Pong {
  bytes reqId = 1;
  bytes toIp = 2;
}

message FindNodes {
  bytes reqId = 1;
  bytes session = 2;
  bytes targetId = 3;
}

message Nodes {
  bytes reqId = 1;
  repeated Node  nodes = 2;
}